<div class="post-page-cont">
    <div class="main-cont-col main-cont-col--1"></div>
    <div class="main-cont-col main-cont-col--2"></div>
    <div class="main-cont-col main-cont-col--3"></div>
    <?php
    require_once $dimport["db/db_funcs.php"]["path"];
    require_once $dimport["security/csrf_prevent.php"]["path"];

    require_once $dimport["post/filter_post.php"]["path"];
    $query_post = "SELECT * FROM $table
                   $filter_query
                   ORDER BY $order_by DESC
                   LIMIT $pagin_start,$pagin_amt;";

    $posts = $sql_query($query_post, [$search, $search]);
    require_once $dimport["post/posts.phtml"]["path"];
    ?>
</div>

<?php require_once $dimport["media/pagin.phtml"]["path"];
