<?php
session_start();
require_once $dimport["security/csrf_prevent.php"]["path"];
require_once $dimport["app/main_funcs.php"]["path"];

if (empty($_GET["user-id"]))
    redirect($dimport["home/home_page.phtml"]["redirect"]."&error=invalid-user-id");

require_once $dimport["db/db_funcs.php"]["path"];

$user = $records_get("pd_user", "user_id", $_GET["user-id"]);
if (empty($user)) $get_error_page("User Not Found", "/img/error/no_user.gif");
$user = $user[0];

require_once $dimport["comment/filter_comment.php"]["path"];

$query_comment = "SELECT * FROM $table
                  $filter_query
                  ORDER BY $order_by DESC
                  LIMIT $pagin_start,$pagin_amt;";

$comments = $sql_query($query_comment);

$title = $user["username"]."'s Comments";
require_once $dimport["layouts/header.phtml"]["path"]; ?>

<div class="main-cont thin-cont block-middle">
    <?php
    if (!empty($comments)) {
        require_once $dimport["comment/comment_sort_bar.phtml"]["path"];
        require_once $dimport["comment/comments.phtml"]["path"];
    }
    ?>
</div>

<?php
require_once $dimport["media/pagin.phtml"]["path"];

require_once $dimport["layouts/footer.phtml"]["path"];
